## Начальная предобработка данных

In [77]:
import pandas as pd
import warnings
import matplotlib.pyplot as plt
import ast
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
warnings.filterwarnings("ignore")

In [2]:
all_data = pd.read_csv('mentors_data.xls')
all_data

,id,airtable_id,slug,name,job,workplace,competencies,experience,price,mentee_count,photo_url,tags,sortOrder,isVisible,sponsors,calendarType,isNew
0,2798,reckMOKgyc6upyHwL,nikolay-sheyko-2798,Nikolay Sheyko,CTO,AI и грабли,"['AI', 'LLM', 'ML', 'RAG', 'GPT', 'Google Gemi...",5-10,15000 руб,9,https://dl.airtable.com/.directUploadAttachmen...,"['Data Science/ML', 'Product Management', 'Tea...",1,True,none,none,False
1,4991,recmLN5ebN5ondUnA,elena-galkina-4991,Елена Галкина,СЕО,"""WorldLegalTeam""","['Law', 'Legal', 'Career', 'HR']",10+,Бесплатно,0,https://dl.airtable.com/.directUploadAttachmen...,"['Карьера', 'Собеседования', 'Аналитика', 'HR']",2,True,none,none,False
2,3192,rectT0buN1Xdrj9ah,andrey-protopopov-3192,Андрей Протопопов,Founder / CEO,ReenCar,"['Leadership', 'management', 'product manageme...",10+,По договоренности,2,https://dl.airtable.com/.attachments/2a6abef7c...,"['Entrepreneurship', 'Marketing', 'Team Lead/M...",3,True,none,calendly,False
3,3189,recgQ2QXCnM0haCBV,daniil-dzhumaylo-3189,Даниил Джумайло,Продакт-менеджер,Московская Биржа,"['Agile: Scrum', 'Kanban', 'Project Management...",10+,4000 руб,12,https://dl.airtable.com/.attachments/ae948189e...,"['Product Management', 'Project Management', '...",3,True,none,none,False
4,2754,recZsbR7xtww1Q9vh,zhembe-mihaylov-2754,Жэмбэ Михайлов,Founder | CEO,Friendly Family,['Проведение CustDev Создание прототипа продук...,2-5,По договоренности,2,https://dl.airtable.com/.attachments/810234f07...,['Product Management'],3,True,none,calendly,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3019,5170,recuRSUJZ2Vxr0nan,daniil-poliakov-5170,Даниил Поляков,Head Devops,X5,"['Gitlab', 'ansible', 'docker', 'k8s', 'kubern...",5-10,По договоренности,1,https://dl.airtable.com/.directUploadAttachmen...,"['DevOps/SRE', 'Team Lead/Management']",1000,True,none,none,False
3020,4610,recArZ4VpgqMOfRZb,aleksey-kozlovskiy-4610,Алексей Козловский,Руководитель по организационному развитию и це...,Avito,"['Management', 'Strategy', 'Leadership', 'Care...",10+,По договоренности,4,https://dl.airtable.com/.directUploadAttachmen...,"['Карьера', 'Team Lead/Management', 'Собеседов...",1000,True,Эксперт Авито,none,False
3021,3309,recWbdc4KRG4djmXg,levon-sisakian-3309,Левон Сисакян,Управляющий партнер,Полиметрика,"['Маркетинг', 'Привлечение клиентов', 'Продвиж...",5-10,По договоренности,1,https://dl.airtable.com/.attachments/5910febae...,"['Product Management', 'Marketing', 'Entrepren...",1000,True,none,none,False
3022,2131,rec55sTbhLMyZZVIt,belskih-andrey-2131,Бельских Андрей,тест-менеджер,VK,"['Test Design', 'Jmetre', 'ghz', 'JIRA', 'test...",10+,По договоренности,1,https://dl.airtable.com/.attachments/2533f2526...,"['QA', 'Team Lead/Management']",1000,True,none,none,False
3023,256,rec9de1EoA99XlzwT,sergey-breznev-256,Сергей Брезнев,"Head of User Acquisition, привлечение мобильно...",Red Panda Labs,"['Facebook Ads', 'Google Ads (UAC)', 'TikTok A...",5-10,По договоренности,7,https://dl.airtable.com/.attachments/35001205f...,"['Android', 'iOS', 'Marketing', 'Team Lead/Man...",1000,True,none,none,False

In [3]:
all_data.isna().sum() ## нет пропусков (хорошо)

id              0
airtable_id     0
slug            0
name            0
job             0
workplace       0
competencies    0
experience      0
price           0
mentee_count    0
photo_url       0
tags            0
sortOrder       0
isVisible       0
sponsors        0
calendarType    0
isNew           0
dtype: int64

In [4]:
all_data['isVisible'].sum() / len(all_data) ## ненужный признак, принимает всегда одно значение

np.float64(1.0)

In [5]:
need_data = all_data.drop(['id', 'airtable_id', 'slug', 'name', 'photo_url', 'isVisible'], axis=1) ## фото можно как нибудь потом обработать c попмощью cv
need_data

,job,workplace,competencies,experience,price,mentee_count,tags,sortOrder,sponsors,calendarType,isNew
0,CTO,AI и грабли,"['AI', 'LLM', 'ML', 'RAG', 'GPT', 'Google Gemi...",5-10,15000 руб,9,"['Data Science/ML', 'Product Management', 'Tea...",1,none,none,False
1,СЕО,"""WorldLegalTeam""","['Law', 'Legal', 'Career', 'HR']",10+,Бесплатно,0,"['Карьера', 'Собеседования', 'Аналитика', 'HR']",2,none,none,False
2,Founder / CEO,ReenCar,"['Leadership', 'management', 'product manageme...",10+,По договоренности,2,"['Entrepreneurship', 'Marketing', 'Team Lead/M...",3,none,calendly,False
3,Продакт-менеджер,Московская Биржа,"['Agile: Scrum', 'Kanban', 'Project Management...",10+,4000 руб,12,"['Product Management', 'Project Management', '...",3,none,none,False
4,Founder | CEO,Friendly Family,['Проведение CustDev Создание прототипа продук...,2-5,По договоренности,2,['Product Management'],3,none,calendly,False
...,...,...,...,...,...,...,...,...,...,...,...
3019,Head Devops,X5,"['Gitlab', 'ansible', 'docker', 'k8s', 'kubern...",5-10,По договоренности,1,"['DevOps/SRE', 'Team Lead/Management']",1000,none,none,False
3020,Руководитель по организационному развитию и це...,Avito,"['Management', 'Strategy', 'Leadership', 'Care...",10+,По договоренности,4,"['Карьера', 'Team Lead/Management', 'Собеседов...",1000,Эксперт Авито,none,False
3021,Управляющий партнер,Полиметрика,"['Маркетинг', 'Привлечение клиентов', 'Продвиж...",5-10,По договоренности,1,"['Product Management', 'Marketing', 'Entrepren...",1000,none,none,False
3022,тест-менеджер,VK,"['Test Design', 'Jmetre', 'ghz', 'JIRA', 'test...",10+,По договоренности,1,"['QA', 'Team Lead/Management']",1000,none,none,False
3023,"Head of User Acquisition, привлечение мобильно...",Red Panda Labs,"['Facebook Ads', 'Google Ads (UAC)', 'TikTok A...",5-10,По договоренности,7,"['Android', 'iOS', 'Marketing', 'Team Lead/Man...",1000,none,none,False

## Дальнейшая предобработка

In [6]:
## сначала переведем все нижний регистр(все пишут по разному)
need_data['job'] = need_data['job'].apply(lambda x: x.lower())
need_data['workplace'] = need_data['workplace'].apply(lambda x: x.lower())

need_data['job'].value_counts()

job
product manager                       55
senior product manager                37
cto                                   37
head of product                       28
product owner                         25
                                      ..
тимлид, ex cto                         1
it recruiter                           1
associate data engineer                1
founder (cpo)                          1
chief developer relations officer      1
Name: count, Length: 1947, dtype: int64

In [7]:
need_data['competencies'] = need_data['competencies'].apply(lambda x: ast.literal_eval(x))
need_data['tags'] = need_data['tags'].apply(lambda x: ast.literal_eval(x))
need_data[['competencies', 'tags']]

,competencies,tags
0,"[AI, LLM, ML, RAG, GPT, Google Gemini]","[Data Science/ML, Product Management, Team Lea..."
1,"[Law, Legal, Career, HR]","[Карьера, Собеседования, Аналитика, HR]"
2,"[Leadership, management, product management, d...","[Entrepreneurship, Marketing, Team Lead/Manage..."
3,"[Agile: Scrum, Kanban, Project Management, Pro...","[Product Management, Project Management, Собес..."
4,[Проведение CustDev Создание прототипа продукт...,[Product Management]
...,...,...
3019,"[Gitlab, ansible, docker, k8s, kubernetes, man...","[DevOps/SRE, Team Lead/Management]"
3020,"[Management, Strategy, Leadership, Career mana...","[Карьера, Team Lead/Management, Собеседования,..."
3021,"[Маркетинг, Привлечение клиентов, Продвижение ...","[Product Management, Marketing, Entrepreneursh..."
3022,"[Test Design, Jmetre, ghz, JIRA, testrail, Lea...","[QA, Team Lead/Management]"
3023,"[Facebook Ads, Google Ads (UAC), TikTok Ads, U...","[Android, iOS, Marketing, Team Lead/Management..."

In [8]:
all_tags_data = []
for mentor_tags in need_data['tags']:
    all_tags_data.extend(mentor_tags)
np.unique(all_tags_data)## мало признаков, легче  с ними работать

array(['Agile', 'Android', 'Backend', 'Cloud', 'Code Review',
       'Content/Copy', 'Data Science/ML', 'Databases', 'DevOps/SRE',
       'DevRel', 'Entrepreneurship', 'Frontend', 'HR', 'Marketing',
       'Product Management', 'Project Management', 'QA', 'System Design',
       'Team Lead/Management', 'UX/UI/Design', 'iOS', 'Аналитика',
       'Безопасность', 'Другое', 'Карьера', 'Сети', 'Собеседования',
       'Сообщество Онтико', 'Эксперт Авито'], dtype='<U20')

In [9]:
all_competencies_data = []
for mentor_competencies in need_data['competencies']:
    all_competencies_data.extend(mentor_competencies)
len(np.unique(all_competencies_data)) ## too much признаков, данных маловато, чтобы вытащить какую-то пользу

8328

### посмотрев на данные competencies и tags я сделал вывод, что tags и competencies пересекаются, только в competencies содержатся слишком много значений(почему одни и те же новыки написаны по разному), но в tags все значения записаны одинаково и значений немного, поэтому дропну competencies, оставив только его длину

In [10]:
need_data['competencies_count'] = need_data['competencies'].apply(lambda x: len(x))
need_data.drop(['competencies'], axis=1, inplace=True)
need_data

,job,workplace,experience,price,mentee_count,tags,sortOrder,sponsors,calendarType,isNew,competencies_count
0,cto,ai и грабли,5-10,15000 руб,9,"[Data Science/ML, Product Management, Team Lea...",1,none,none,False,6
1,сео,"""worldlegalteam""",10+,Бесплатно,0,"[Карьера, Собеседования, Аналитика, HR]",2,none,none,False,4
2,founder / ceo,reencar,10+,По договоренности,2,"[Entrepreneurship, Marketing, Team Lead/Manage...",3,none,calendly,False,4
3,продакт-менеджер,московская биржа,10+,4000 руб,12,"[Product Management, Project Management, Собес...",3,none,none,False,13
4,founder | ceo,friendly family,2-5,По договоренности,2,[Product Management],3,none,calendly,False,7
...,...,...,...,...,...,...,...,...,...,...,...
3019,head devops,x5,5-10,По договоренности,1,"[DevOps/SRE, Team Lead/Management]",1000,none,none,False,7
3020,руководитель по организационному развитию и це...,avito,10+,По договоренности,4,"[Карьера, Team Lead/Management, Собеседования,...",1000,Эксперт Авито,none,False,7
3021,управляющий партнер,полиметрика,5-10,По договоренности,1,"[Product Management, Marketing, Entrepreneursh...",1000,none,none,False,7
3022,тест-менеджер,vk,10+,По договоренности,1,"[QA, Team Lead/Management]",1000,none,none,False,13
3023,"head of user acquisition, привлечение мобильно...",red panda labs,5-10,По договоренности,7,"[Android, iOS, Marketing, Team Lead/Management...",1000,none,none,False,7

In [11]:
## методом пристального взгляда видим, что все данные из job содержатся в tags по смыслу, так что колонку
## пример: job - head devops, tags - [DevOps/SRE, Team Lead/Management]
need_data.drop(['job'], axis=1, inplace=True)
need_data

,workplace,experience,price,mentee_count,tags,sortOrder,sponsors,calendarType,isNew,competencies_count
0,ai и грабли,5-10,15000 руб,9,"[Data Science/ML, Product Management, Team Lea...",1,none,none,False,6
1,"""worldlegalteam""",10+,Бесплатно,0,"[Карьера, Собеседования, Аналитика, HR]",2,none,none,False,4
2,reencar,10+,По договоренности,2,"[Entrepreneurship, Marketing, Team Lead/Manage...",3,none,calendly,False,4
3,московская биржа,10+,4000 руб,12,"[Product Management, Project Management, Собес...",3,none,none,False,13
4,friendly family,2-5,По договоренности,2,[Product Management],3,none,calendly,False,7
...,...,...,...,...,...,...,...,...,...,...
3019,x5,5-10,По договоренности,1,"[DevOps/SRE, Team Lead/Management]",1000,none,none,False,7
3020,avito,10+,По договоренности,4,"[Карьера, Team Lead/Management, Собеседования,...",1000,Эксперт Авито,none,False,7
3021,полиметрика,5-10,По договоренности,1,"[Product Management, Marketing, Entrepreneursh...",1000,none,none,False,7
3022,vk,10+,По договоренности,1,"[QA, Team Lead/Management]",1000,none,none,False,13
3023,red panda labs,5-10,По договоренности,7,"[Android, iOS, Marketing, Team Lead/Management...",1000,none,none,False,7

In [12]:
need_data['isNew'].sum() ## видно, что всего один человек с новым аккаунтом, тоже дропнем колонку

np.int64(1)

In [13]:
need_data.drop(['isNew'], axis=1, inplace=True)
need_data

,workplace,experience,price,mentee_count,tags,sortOrder,sponsors,calendarType,competencies_count
0,ai и грабли,5-10,15000 руб,9,"[Data Science/ML, Product Management, Team Lea...",1,none,none,6
1,"""worldlegalteam""",10+,Бесплатно,0,"[Карьера, Собеседования, Аналитика, HR]",2,none,none,4
2,reencar,10+,По договоренности,2,"[Entrepreneurship, Marketing, Team Lead/Manage...",3,none,calendly,4
3,московская биржа,10+,4000 руб,12,"[Product Management, Project Management, Собес...",3,none,none,13
4,friendly family,2-5,По договоренности,2,[Product Management],3,none,calendly,7
...,...,...,...,...,...,...,...,...,...
3019,x5,5-10,По договоренности,1,"[DevOps/SRE, Team Lead/Management]",1000,none,none,7
3020,avito,10+,По договоренности,4,"[Карьера, Team Lead/Management, Собеседования,...",1000,Эксперт Авито,none,7
3021,полиметрика,5-10,По договоренности,1,"[Product Management, Marketing, Entrepreneursh...",1000,none,none,7
3022,vk,10+,По договоренности,1,"[QA, Team Lead/Management]",1000,none,none,13
3023,red panda labs,5-10,По договоренности,7,"[Android, iOS, Marketing, Team Lead/Management...",1000,none,none,7

In [14]:
need_data['sponsors'].value_counts() ## тут на всякий заменим на dummy-переменную have_sponsor

sponsors
none                               2869
Эксперт Авито                       106
Сообщество Онтико                    48
Эксперт Авито|Сообщество Онтико       1
Name: count, dtype: int64

In [15]:
need_data['have_sponsor'] = (need_data['sponsors'] != 'none').astype('int')
need_data.drop(['sponsors'], axis=1, inplace=True)
need_data

,workplace,experience,price,mentee_count,tags,sortOrder,calendarType,competencies_count,have_sponsor
0,ai и грабли,5-10,15000 руб,9,"[Data Science/ML, Product Management, Team Lea...",1,none,6,0
1,"""worldlegalteam""",10+,Бесплатно,0,"[Карьера, Собеседования, Аналитика, HR]",2,none,4,0
2,reencar,10+,По договоренности,2,"[Entrepreneurship, Marketing, Team Lead/Manage...",3,calendly,4,0
3,московская биржа,10+,4000 руб,12,"[Product Management, Project Management, Собес...",3,none,13,0
4,friendly family,2-5,По договоренности,2,[Product Management],3,calendly,7,0
...,...,...,...,...,...,...,...,...,...
3019,x5,5-10,По договоренности,1,"[DevOps/SRE, Team Lead/Management]",1000,none,7,0
3020,avito,10+,По договоренности,4,"[Карьера, Team Lead/Management, Собеседования,...",1000,none,7,1
3021,полиметрика,5-10,По договоренности,1,"[Product Management, Marketing, Entrepreneursh...",1000,none,7,0
3022,vk,10+,По договоренности,1,"[QA, Team Lead/Management]",1000,none,13,0
3023,red panda labs,5-10,По договоренности,7,"[Android, iOS, Marketing, Team Lead/Management...",1000,none,7,0

In [ ]:
need_data['calendarType'].value_counts() ## заменим на have_calendar

calendarType
none         2487
calendly      354
url           158
koalendar      25
Name: count, dtype: int64

In [35]:
need_data['have_calendar'] = (need_data['calendarType'] != 'none').astype('int')
need_data.drop('calendarType', axis=1, inplace=True)
need_data

,workplace,experience,price,mentee_count,sortOrder,competencies_count,have_sponsor,is_Agile,is_Android,is_Backend,...,is_iOS,is_Аналитика,is_Безопасность,is_Другое,is_Карьера,is_Сети,is_Собеседования,is_Сообщество Онтико,is_Эксперт Авито,have_calendar
0,ai и грабли,5-10,15000 руб,9,1,6,0,0,0,0,...,0,0,0,0,1,0,1,0,0,0
1,"""worldlegalteam""",10+,Бесплатно,0,2,4,0,0,0,0,...,0,1,0,0,1,0,1,0,0,0
2,reencar,10+,По договоренности,2,3,4,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,московская биржа,10+,4000 руб,12,3,13,0,1,0,0,...,0,0,0,0,1,0,1,0,0,0
4,friendly family,2-5,По договоренности,2,3,7,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3019,x5,5-10,По договоренности,1,1000,7,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3020,avito,10+,По договоренности,4,1000,7,1,0,0,0,...,0,0,0,0,1,0,1,0,1,0
3021,полиметрика,5-10,По договоренности,1,1000,7,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
3022,vk,10+,По договоренности,1,1000,13,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3023,red panda labs,5-10,По договоренности,7,1000,7,0,0,1,0,...,1,1,0,1,0,0,1,0,0,0

In [ ]:
need_data['experience'].value_counts() # логичная колонка

experience
10+     1457
5-10    1139
2-5      428
Name: count, dtype: int64

In [24]:
## сделаем dummy-переменные
uniq_tags = np.unique(all_tags_data)
for uniq_tag in uniq_tags:
    need_data[f'is_{uniq_tag}'] = need_data['tags'].apply(lambda x: uniq_tag in x).astype('int')
need_data.drop('tags', axis=1, inplace=True)
need_data

,workplace,experience,price,mentee_count,sortOrder,calendarType,competencies_count,have_sponsor,is_Agile,is_Android,...,is_UX/UI/Design,is_iOS,is_Аналитика,is_Безопасность,is_Другое,is_Карьера,is_Сети,is_Собеседования,is_Сообщество Онтико,is_Эксперт Авито
0,ai и грабли,5-10,15000 руб,9,1,none,6,0,0,0,...,0,0,0,0,0,1,0,1,0,0
1,"""worldlegalteam""",10+,Бесплатно,0,2,none,4,0,0,0,...,0,0,1,0,0,1,0,1,0,0
2,reencar,10+,По договоренности,2,3,calendly,4,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,московская биржа,10+,4000 руб,12,3,none,13,0,1,0,...,0,0,0,0,0,1,0,1,0,0
4,friendly family,2-5,По договоренности,2,3,calendly,7,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3019,x5,5-10,По договоренности,1,1000,none,7,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3020,avito,10+,По договоренности,4,1000,none,7,1,0,0,...,0,0,0,0,0,1,0,1,0,1
3021,полиметрика,5-10,По договоренности,1,1000,none,7,0,0,0,...,0,0,1,0,0,0,0,0,0,0
3022,vk,10+,По договоренности,1,1000,none,13,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3023,red panda labs,5-10,По договоренности,7,1000,none,7,0,0,1,...,0,1,1,0,1,0,0,1,0,0

In [ ]:
need_data['workplace'].value_counts()[:20]
no_data_symb = ['-', 'NDA']
freelance_symb = ['Freelance', 'Самозанятый', 'Фриланс', 'Outstaff + Freelance', 'Самозанятость']

need_data['workplace'].value_counts()[:20]

workplace
авито                    62
яндекс                   54
avito                    39
сбер                     39
т-банк                   28
yandex                   26
vk                       26
альфа-банк               23
wildberries              17
-                        16
ozon                     15
nda                      14
фриланс                  13
positive technologies    13
tinkoff                  12
freelance                12
вконтакте                11
мтс                      11
ozon tech                10
яндекс практикум          9
Name: count, dtype: int64

In [ ]:
## сделаем колонку для биг теха
big_tech = ['авито','яндекс','avito','сбер','т-банк','yandex','vk','альфа-банк',
            'wildberries','ozon', 'positive technologies', 'tinkoff', 'вконтакте',
            'мтс', 'ozon tech', 'яндекс практикум', 't-bank', 'тинькофф', 'альфа банк',
            'mts digital', 'мтс диджитал', 'sber', 't-банк', 'сберздоровье', 'сбербанк', 'яндекс.практикум',
            'тбанк', 'yandex cloud', 'сбермаркет', 'ex-yandex','ozon bank', 'купер', 'sberbank',
            'zvuk.com', 'авито тех', 'мтс финтех', 'вк', 'альфабанк', 'озон технологии',
            'мтс big data', 'ex-yandex, ex-avito', 't-страхование', 'wildberries', 'microsoft', 'мтс юрент',
            'alfa-bank', 'пао сбербанк', 'яндекс маркет', 'сберавто', 'т-банк(ex тинькофф)',
            'ozon fresh', 'alfa-bank',
            'fintech | ex-zvuk, ex-lamoda, ex-yandex', 'avito ex. tbank, ex. yandex, ex. vk', 'ex сбермаркет', 'сбер, х5 retail, иннотех, атом',
            'яндекс лавка', 'vk video (вконтакте)', 'wildberries [ex sber, alfabank, modulbank]', 'apple', 'amazon', 'revolut']

need_data['is_big_tech'] = 0
for comp_name in big_tech:

    need_data['is_big_tech'] = need_data['is_big_tech'] | need_data['workplace'].apply(lambda x: comp_name in x).astype('int')
need_data

,workplace,experience,price,mentee_count,sortOrder,competencies_count,have_sponsor,is_Agile,is_Android,is_Backend,...,is_Аналитика,is_Безопасность,is_Другое,is_Карьера,is_Сети,is_Собеседования,is_Сообщество Онтико,is_Эксперт Авито,have_calendar,is_big_tech
0,ai и грабли,5-10,15000 руб,9,1,6,0,0,0,0,...,0,0,0,1,0,1,0,0,0,0
1,"""worldlegalteam""",10+,Бесплатно,0,2,4,0,0,0,0,...,1,0,0,1,0,1,0,0,0,0
2,reencar,10+,По договоренности,2,3,4,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,московская биржа,10+,4000 руб,12,3,13,0,1,0,0,...,0,0,0,1,0,1,0,0,0,0
4,friendly family,2-5,По договоренности,2,3,7,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3019,x5,5-10,По договоренности,1,1000,7,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3020,avito,10+,По договоренности,4,1000,7,1,0,0,0,...,0,0,0,1,0,1,0,1,0,1
3021,полиметрика,5-10,По договоренности,1,1000,7,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
3022,vk,10+,По договоренности,1,1000,13,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3023,red panda labs,5-10,По договоренности,7,1000,7,0,0,1,0,...,1,0,1,0,0,1,0,0,0,0

In [69]:
need_data['is_big_tech'].mean()
need_data.drop('workplace', axis=1, inplace=True)
need_data

,experience,price,mentee_count,sortOrder,competencies_count,have_sponsor,is_Agile,is_Android,is_Backend,is_Cloud,...,is_Аналитика,is_Безопасность,is_Другое,is_Карьера,is_Сети,is_Собеседования,is_Сообщество Онтико,is_Эксперт Авито,have_calendar,is_big_tech
0,5-10,15000 руб,9,1,6,0,0,0,0,0,...,0,0,0,1,0,1,0,0,0,0
1,10+,Бесплатно,0,2,4,0,0,0,0,0,...,1,0,0,1,0,1,0,0,0,0
2,10+,По договоренности,2,3,4,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,10+,4000 руб,12,3,13,0,1,0,0,0,...,0,0,0,1,0,1,0,0,0,0
4,2-5,По договоренности,2,3,7,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3019,5-10,По договоренности,1,1000,7,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3020,10+,По договоренности,4,1000,7,1,0,0,0,0,...,0,0,0,1,0,1,0,1,0,1
3021,5-10,По договоренности,1,1000,7,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
3022,10+,По договоренности,1,1000,13,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3023,5-10,По договоренности,7,1000,7,0,0,1,0,0,...,1,0,1,0,0,1,0,0,0,0

## Делим на трейн и тест

In [73]:
test = need_data[need_data['price'] == 'По договоренности'] ## тестовые данные возьмем как те, в которых цены не прописаны
full_train = need_data[need_data['price'] != 'По договоренности']

In [74]:
## заменяем бесплатно на 0
full_train.loc[full_train['price'] == 'Бесплатно', 'price'] = '0 руб'
## убираем 'руб' в конце(переводим в числовой формат)
full_train['price'] = full_train['price'].apply(lambda x: x.split()[0]).astype('int')
full_train['price'] ## все цены числовые

0       15000
1           0
3        4000
6        2000
7        3000
        ...
2999     6000
3001     9000
3005     7000
3007     5000
3013        0
Name: price, Length: 1820, dtype: int64

In [75]:
X_full_train, y_full_train = full_train.drop('price', axis=1), full_train['price']
X_test = test.drop('price', axis=1)
X_full_train.shape, X_test.shape ## тест немного большеват, но что поделать(

((1820, 36), (1204, 36))

,experience,mentee_count,sortOrder,competencies_count,have_sponsor,is_Agile,is_Android,is_Backend,is_Cloud,is_Code Review,...,is_Аналитика,is_Безопасность,is_Другое,is_Карьера,is_Сети,is_Собеседования,is_Сообщество Онтико,is_Эксперт Авито,have_calendar,is_big_tech
0,5-10,9,1,6,0,0,0,0,0,0,...,0,0,0,1,0,1,0,0,0,0
1,10+,0,2,4,0,0,0,0,0,0,...,1,0,0,1,0,1,0,0,0,0
3,10+,12,3,13,0,1,0,0,0,0,...,0,0,0,1,0,1,0,0,0,0
6,5-10,1,4,20,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,2-5,0,4,3,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2999,10+,44,992,5,0,0,0,0,0,0,...,0,0,0,1,0,1,0,0,0,0
3001,10+,13,992,9,1,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
3005,5-10,8,993,8,0,0,0,0,0,0,...,0,0,0,1,0,1,0,0,1,0
3007,10+,1,995,6,0,0,0,0,0,0,...,0,0,0,1,0,1,0,0,0,1
3013,10+,0,998,3,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## Графики

## predictions

In [78]:
from autogluon.tabular import TabularPredictor
label = 'price'
train_df, val_df = train_test_split(
    full_train, test_size=0.2, random_state=42
)

predictor = TabularPredictor(
    label=label,
    problem_type='regression',
    eval_metric='mae'  # ключевая метрика
)

predictor.fit(
    train_data=train_df,
    presets='best_quality',
    num_bag_folds=5,
    num_stack_levels=1)

# 4) Оценка на валидации/тесте
leaderboard = predictor.leaderboard(val_df, silent=True)
print(leaderboard)

performance = predictor.evaluate(val_df)  # выведет MAE (и др. метрики)
print("MAE:", performance["mae"])

# 5) Предсказания
y_pred_val = predictor.predict(val_df.drop(columns=[label]))
print(y_pred_val.head())

# 6) Важность признаков (полезно для интерпретации)
fi = predictor.feature_importance(val_df)
print(fi.head(20))

No path specified. Models will be saved in: "AutogluonModels\ag-20250904_075606"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.4.0
Python Version:     3.11.13
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26100
CPU Count:          12
Memory Avail:       1.13 GB / 7.72 GB (14.6%)
Disk Space Avail:   16.35 GB / 120.00 GB (13.6%)
===================================================
Presets specified: ['best_quality']
Using hyperparameters preset: hyperparameters='zeroshot'
Setting dynamic_stacking from 'auto' to True. Reason: Enable dynamic_stacking when use_bag_holdout is disabled. (use_bag_holdout=False)
Stack configuration (auto_stack=True): num_stack_levels=1, num_bag_folds=5, num_bag_sets=1
DyStack is enabled (dynamic_stacking=True). AutoGluon will try to determine whether the input data is affected by stacked overfitting and enable or disable stacking as a consequence.
	This is used to identify the optimal `num_stack_levels` value. Copies of AutoGluon will be fit on subsets of the data. Then holdout validation data is used to detect stacked overfitting.
	Running DyStack for up to 900s of the 3600s of remaining time (25%).
2025-09-04 10:56:08,515	INFO util.py:154 -- Missing packages: ['ipywidgets']. Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.
	Running DyStack sub-fit in a ray process to avoid memory leakage. Enabling ray logging (enable_ray_logging=True). Specify `ds_args={'enable_ray_logging': False}` if you experience logging issues.
2025-09-04 10:56:14,297	INFO worker.py:1843 -- Started a local Ray instance. View the dashboard at http://127.0.0.1:8265
		Context path: "c:\Users\123в\git_rep_bot\AutogluonModels\ag-20250904_075606\ds_sub_fit\sub_fit_ho"
(_dystack pid=26772) Running DyStack sub-fit ...

KeyboardInterrupt:

(_dystack pid=26772) Beginning AutoGluon training ... Time limit = 890s
(_dystack pid=26772) AutoGluon will save models to "c:\Users\123в\git_rep_bot\AutogluonModels\ag-20250904_075606\ds_sub_fit\sub_fit_ho"
(_dystack pid=26772) Train Data Rows:    1294
(_dystack pid=26772) Train Data Columns: 36
(_dystack pid=26772) Label Column:       price
(_dystack pid=26772) Problem Type:       regression
(_dystack pid=26772) Preprocessing data ...
(_dystack pid=26772) Using Feature Generators to preprocess the data ...
(_dystack pid=26772) Fitting AutoMLPipelineFeatureGenerator...
(_dystack pid=26772) 	Available Memory:                    1169.85 MB
(_dystack pid=26772) 	Train Data (Original)  Memory Usage: 0.42 MB (0.0% of available memory)
(_dystack pid=26772) 	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
(_dystack pid=26772) 	Stage 1 Generators:
(_dystack pid=26772) 		Fitting AsTypeFeatureGenerator...
(_dystack pid=26772) 			Note: Converting 32 features to boolean dtype as they only contain 2 unique values.
(_dystack pid=26772) 	Stage 2 Generators:
(_dystack pid=26772) 		Fitting FillNaFeatureGenerator...
(_dystack pid=26772) 	Stage 3 Generators:
(_dystack pid=26772) 		Fitting IdentityFeatureGenerator...
(_dystack pid=26772) 		Fitting CategoryFeatureGenerator...
(_dystack pid=26772) 			Fitting CategoryMemoryMinimizeFeatureGenerator...
(_dystack pid=26772) 	Stage 4 Generators:
(_dystack pid=26772) 		Fitting DropUniqueFeatureGenerator...
(_dystack pid=26772) 	Stage 5 Generators:
(_dystack pid=26772) 		Fitting DropDuplicatesFeatureGenerator...
(_dystack pid=26772) 	Types of features in original data (raw dtype, special dtypes):
(_dystack pid=26772) 		('int', [])    : 35 | ['mentee_count', 'sortOrder', 'competencies_count', 'have_sponsor', 'is_Agile', ...]
(_dystack pid=26772) 		('object', []) :  1 | ['experience']
(_dystack pid=26772) 	Types of features in processed data (raw dtype, special dtypes):
(_dystack pid=26772) 		('category', [])  :  1 | ['experience']
(_dystack pid=26772) 		('int', [])       :  3 | ['mentee_count', 'sortOrder', 'competencies_count']
(_dystack pid=26772) 		('int', ['bool']) : 32 | ['have_sponsor', 'is_Agile', 'is_Android', 'is_Backend', 'is_Cloud', ...]
(_dystack pid=26772) 	0.1s = Fit runtime
(_dystack pid=26772) 	36 features in original data used to generate 36 features in processed data.
(_dystack pid=26772) 	Train Data (Processed) Memory Usage: 0.07 MB (0.0% of available memory)
(_dystack pid=26772) Data preprocessing and feature engineering runtime = 0.07s ...
(_dystack pid=26772) AutoGluon will gauge predictive performance using evaluation metric: 'mean_absolute_error'
(_dystack pid=26772) 	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
(_dystack pid=26772) 	To change this, specify the eval_metric parameter of Predictor()
(_dystack pid=26772) Large model count detected (110 configs) ... Only displaying the first 3 models of each family. To see all, set `verbosity=3`.
(_dystack pid=26772) User-specified model hyperparameters to be fit:
(_dystack pid=26772) {
(_dystack pid=26772) 	'NN_TORCH': [{}, {'activation': 'elu', 'dropout_prob': 0.10077639529843717, 'hidden_size': 108, 'learning_rate': 0.002735937344002146, 'num_layers': 4, 'use_batchnorm': True, 'weight_decay': 1.356433327634438e-12, 'ag_args': {'name_suffix': '_r79', 'priority': -2}}, {'activation': 'elu', 'dropout_prob': 0.11897478034205347, 'hidden_size': 213, 'learning_rate': 0.0010474382260641949, 'num_layers': 4, 'use_batchnorm': False, 'weight_decay': 5.594471067786272e-10, 'ag_args': {'name_suffix': '_r22', 'priority': -7}}],
(_dystack pid=26772) 	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
(_dystack pid=26772) 	'CAT': [{}, {'depth': 6, 'grow_policy': 'SymmetricTree', 'l2_leaf_reg': 2.1542798306067823, 'learning_rate': 0.06864209415792857, 'max_ctr_complexity': 4, 'one_hot_max_size': 10, 'ag_args': {'name_suffix': '_r177', 'priority': -1}}, {'depth': 8, 'grow_policy': 'Depthwise', 'l2_leaf_reg': 2.7997999596449104, 'learning_rate': 0.031375015734637225, 'max_ctr_complexity': 2, 'one_hot_max_size': 3, 'ag_args': {'name_suffix': '_r9', 'priority': -5}}],
(_dystack pid=26772) 	'XGB': [{}, {'colsample_bytree': 0.6917311125174739, 'enable_categorical': False, 'learning_rate': 0.018063876087523967, 'max_depth': 10, 'min_child_weight': 0.6028633586934382, 'ag_args': {'name_suffix': '_r33', 'priority': -8}}, {'colsample_bytree': 0.6628423832084077, 'enable_categorical': False, 'learning_rate': 0.08775715546881824, 'max_depth': 5, 'min_child_weight': 0.6294123374222513, 'ag_args': {'name_suffix': '_r89', 'priority': -16}}],
(_dystack pid=26772) 	'FASTAI': [{}, {'bs': 256, 'emb_drop': 0.5411770367537934, 'epochs': 43, 'layers': [800, 400], 'lr': 0.01519848858318159, 'ps': 0.23782946566604385, 'ag_args': {'name_suffix': '_r191', 'priority': -4}}, {'bs': 2048, 'emb_drop': 0.05070411322605811, 'epochs': 29, 'layers': [200, 100], 'lr': 0.08974235041576624, 'ps': 0.10393466140748028, 'ag_args': {'name_suffix': '_r102', 'priority': -11}}],
(_dystack pid=26772) 	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
(_dystack pid=26772) 	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
(_dystack pid=26772) }
(_dystack pid=26772) AutoGluon will fit 2 stack levels (L1 to L2) ...
(_dystack pid=26772) Fitting 106 L1 models, fit_strategy="sequential" ...
(_dystack pid=26772) Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 592.97s of the 889.66s of remaining time.
(_dystack pid=26772) 	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=2, gpus=0, memory=1.28%)
(_dystack pid=26772) 	-1781.3202	 = Validation score   (-mean_absolute_error)
(_dystack pid=26772) 	1.55s	 = Training   runtime
(_dystack pid=26772) 	0.02s	 = Validation runtime
(_dystack pid=26772) Fitting model: LightGBM_BAG_L1 ... Training model for up to 575.28s of the 871.98s of remaining time.
(_dystack pid=26772) 	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=2, gpus=0, memory=1.34%)
(_dystack pid=26772) 	-1793.9896	 = Validation score   (-mean_absolute_error)
(_dystack pid=26772) 	1.17s	 = Training   runtime
(_dystack pid=26772) 	0.02s	 = Validation runtime
(_dystack pid=26772) Fitting model: RandomForestMSE_BAG_L1 ... Training model for up to 569.49s of the 866.19s of remaining time.
(_dystack pid=26772) 	-1828.4169	 = Validation score   (-mean_absolute_error)
(_dystack pid=26772) 	1.46s	 = Training   runtime
(_dystack pid=26772) 	0.09s	 = Validation runtime
(_dystack pid=26772) Fitting model: CatBoost_BAG_L1 ... Training model for up to 567.87s of the 864.57s of remaining time.
(_dystack pid=26772) 	Memory not enough to fit 5 folds in parallel. Will train 2 folds in parallel instead (Estimated 25.99% memory usage per fold, 51.97%/80.00% total).
(_dystack pid=26772) 	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=6, gpus=0, memory=25.99%)
(_dystack pid=26772) 	-1749.4738	 = Validation score   (-mean_absolute_error)
(_dystack pid=26772) 	58.42s	 = Training   runtime
(_dystack pid=26772) 	0.02s	 = Validation runtime
(_dystack pid=26772) Fitting model: ExtraTreesMSE_BAG_L1 ... Training model for up to 506.30s of the 803.00s of remaining time.
(_dystack pid=26772) 	-1839.5043	 = Validation score   (-mean_absolute_error)
(_dystack pid=26772) 	0.82s	 = Training   runtime
(_dystack pid=26772) 	0.09s	 = Validation runtime
(_dystack pid=26772) Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 505.32s of the 802.02s of remaining time.
(_dystack pid=26772) 	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=2, gpus=0, memory=0.09%)
(_ray_fit pid=21780) No improvement since epoch 3: early stopping
(_dystack pid=26772) 	-1865.1785	 = Validation score   (-mean_absolute_error)
(_dystack pid=26772) 	12.16s	 = Training   runtime
(_dystack pid=26772) 	0.08s	 = Validation runtime
(_dystack pid=26772) Fitting model: XGBoost_BAG_L1 ... Training model for up to 488.88s of the 785.58s of remaining time.
(_dystack pid=26772) 	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=2, gpus=0, memory=1.75%)
(_dystack pid=26772) 	-1793.2152	 = Validation score   (-mean_absolute_error)
(_dystack pid=26772) 	1.17s	 = Training   runtime
(_dystack pid=26772) 	0.04s	 = Validation runtime
(_dystack pid=26772) Fitting model: NeuralNetTorch_BAG_L1 ... Training model for up to 482.84s of the 779.54s of remaining time.
(_dystack pid=26772) 	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=2, gpus=0, memory=0.03%)
(_ray_fit pid=22124) No improvement since epoch 6: early stopping [repeated 4x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/user-guides/configure-logging.html#log-deduplication for more options.)
(_ray_fit pid=12160) c:\Users\123в\git_rep_bot\.conda\Lib\site-packages\sklearn\compose\_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
(_ray_fit pid=12160)   warnings.warn(
(_dystack pid=26772) 	-1754.7244	 = Validation score   (-mean_absolute_error)
(_dystack pid=26772) 	16.34s	 = Training   runtime
(_dystack pid=26772) 	0.06s	 = Validation runtime
(_dystack pid=26772) Fitting model: LightGBMLarge_BAG_L1 ... Training model for up to 462.20s of the 758.90s of remaining time.
(_ray_fit pid=24140) c:\Users\123в\git_rep_bot\.conda\Lib\site-packages\sklearn\compose\_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning. [repeated 4x across cluster]
(_ray_fit pid=24140)   warnings.warn( [repeated 4x across cluster]
(_dystack pid=26772) 	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=2, gpus=0, memory=2.01%)
(_dystack pid=26772) 	-1818.751	 = Validation score   (-mean_absolute_error)
(_dystack pid=26772) 	1.86s	 = Training   runtime
(_dystack pid=26772) 	0.02s	 = Validation runtime
(_dystack pid=26772) Fitting model: CatBoost_r177_BAG_L1 ... Training model for up to 455.47s of the 752.16s of remaining time.
(_dystack pid=26772) 	Memory not enough to fit 5 folds in parallel. Will train 2 folds in parallel instead (Estimated 29.28% memory usage per fold, 58.55%/80.00% total).
(_dystack pid=26772) 	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=6, gpus=0, memory=29.28%)
(_dystack pid=26772) 	-1743.6599	 = Validation score   (-mean_absolute_error)
(_dystack pid=26772) 	10.77s	 = Training   runtime
(_dystack pid=26772) 	0.02s	 = Validation runtime
(_dystack pid=26772) Fitting model: NeuralNetTorch_r79_BAG_L1 ... Training model for up to 441.71s of the 738.41s of remaining time.
(_dystack pid=26772) 	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=2, gpus=0, memory=0.03%)
(_ray_fit pid=22488) c:\Users\123в\git_rep_bot\.conda\Lib\site-packages\sklearn\compose\_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
(_ray_fit pid=22488)   warnings.warn(
(_dystack pid=26772) 	-1815.7516	 = Validation score   (-mean_absolute_error)
(_dystack pid=26772) 	15.67s	 = Training   runtime
(_dystack pid=26772) 	0.07s	 = Validation runtime
(_dystack pid=26772) Fitting model: LightGBM_r131_BAG_L1 ... Training model for up to 421.86s of the 718.55s of remaining time.
(_dystack pid=26772) 	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=2, gpus=0, memory=0.99%)
(_ray_fit pid=10568) c:\Users\123в\git_rep_bot\.conda\Lib\site-packages\sklearn\compose\_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning. [repeated 4x across cluster]
(_ray_fit pid=10568)   warnings.warn( [repeated 4x across cluster]
(_dystack pid=26772) 	-1785.9695	 = Validation score   (-mean_absolute_error)
(_dystack pid=26772) 	1.98s	 = Training   runtime
(_dystack pid=26772) 	0.04s	 = Validation runtime
(_dystack pid=26772) Fitting model: NeuralNetFastAI_r191_BAG_L1 ... Training model for up to 415.48s of the 712.18s of remaining time.
(_dystack pid=26772) 	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=2, gpus=0, memory=0.09%)
(_ray_fit pid=27488) No improvement since epoch 0: early stopping
(_dystack pid=26772) 	-1929.2291	 = Validation score   (-mean_absolute_error)
(_dystack pid=26772) 	17.59s	 = Training   runtime
(_dystack pid=26772) 	0.24s	 = Validation runtime
(_dystack pid=26772) Fitting model: CatBoost_r9_BAG_L1 ... Training model for up to 393.57s of the 690.26s of remaining time.
(_dystack pid=26772) 	Memory not enough to fit 5 folds in parallel. Will train 1 folds in parallel instead (Estimated 59.78% memory usage per fold, 59.78%/80.00% total).
(_dystack pid=26772) 	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (1 workers, per: cpus=8, gpus=0, memory=59.78%)
(_dystack pid=26772) 		Switching to pseudo sequential ParallelFoldFittingStrategy to avoid Python memory leakage.
(_dystack pid=26772) 		Overrule this behavior by setting fold_fitting_strategy to 'sequential_local' in ag_args_ensemble when when calling `predictor.fit`
(_dystack pid=26772) 	-1737.9146	 = Validation score   (-mean_absolute_error)
(_dystack pid=26772) 	48.14s	 = Training   runtime
(_dystack pid=26772) 	0.03s	 = Validation runtime
(_dystack pid=26772) Fitting model: LightGBM_r96_BAG_L1 ... Training model for up to 341.67s of the 638.37s of remaining time.
(_dystack pid=26772) 	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=2, gpus=0, memory=0.99%)
(_ray_fit pid=18448) No improvement since epoch 6: early stopping [repeated 4x across cluster]
(_ray_fit pid=27100) Warning: Low available memory may cause OOM error if training continues
(_ray_fit pid=27100) Available Memory: 120 MB
(_ray_fit pid=27100) Estimated GBM model size: 0 MB
(_ray_fit pid=27100) Warning: Early stopped GBM model prior to optimal result to avoid OOM error. Please increase available memory to avoid subpar model quality.
(_dystack pid=26772) 	-1964.5441	 = Validation score   (-mean_absolute_error)
(_dystack pid=26772) 	0.82s	 = Training   runtime
(_dystack pid=26772) 	0.03s	 = Validation runtime
(_dystack pid=26772) Fitting model: NeuralNetTorch_r22_BAG_L1 ... Training model for up to 335.57s of the 632.27s of remaining time.
(_dystack pid=26772) 	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=2, gpus=0, memory=0.53%)
(_ray_fit pid=10052) c:\Users\123в\git_rep_bot\.conda\Lib\site-packages\sklearn\compose\_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
(_ray_fit pid=10052)   warnings.warn(
(_ray_fit pid=25052) Warning: Low available memory may cause OOM error if training continues [repeated 4x across cluster]
(_ray_fit pid=25052) Available Memory: 96 MB [repeated 4x across cluster]
(_ray_fit pid=25052) Estimated GBM model size: 0 MB [repeated 4x across cluster]
(_ray_fit pid=25052) Warning: Early stopped GBM model prior to optimal result to avoid OOM error. Please increase available memory to avoid subpar model quality. [repeated 4x across cluster]
(_dystack pid=26772) 	-1744.1638	 = Validation score   (-mean_absolute_error)
(_dystack pid=26772) 	24.88s	 = Training   runtime
(_dystack pid=26772) 	0.08s	 = Validation runtime
(_dystack pid=26772) Fitting model: XGBoost_r33_BAG_L1 ... Training model for up to 305.83s of the 602.53s of remaining time.
(_ray_fit pid=14668) c:\Users\123в\git_rep_bot\.conda\Lib\site-packages\sklearn\compose\_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning. [repeated 4x across cluster]
(_ray_fit pid=14668)   warnings.warn( [repeated 4x across cluster]
(_dystack pid=26772) 	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=2, gpus=0, memory=12.48%)
(_dystack pid=26772) 	-1796.2583	 = Validation score   (-mean_absolute_error)
(_dystack pid=26772) 	1.98s	 = Training   runtime
(_dystack pid=26772) 	0.05s	 = Validation runtime
(_dystack pid=26772) Fitting model: ExtraTrees_r42_BAG_L1 ... Training model for up to 298.78s of the 595.47s of remaining time.
(_dystack pid=26772) 	-1841.7295	 = Validation score   (-mean_absolute_error)
(_dystack pid=26772) 	1.05s	 = Training   runtime
(_dystack pid=26772) 	0.11s	 = Validation runtime
(_dystack pid=26772) Fitting model: CatBoost_r137_BAG_L1 ... Training model for up to 297.54s of the 594.23s of remaining time.
(_dystack pid=26772) 	Memory not enough to fit 5 folds in parallel. Will train 2 folds in parallel instead (Estimated 28.43% memory usage per fold, 56.85%/80.00% total).
(_dystack pid=26772) 	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=6, gpus=0, memory=28.43%)
(_dystack pid=26772) 	-1740.3439	 = Validation score   (-mean_absolute_error)
(_dystack pid=26772) 	12.18s	 = Training   runtime
(_dystack pid=26772) 	0.02s	 = Validation runtime
(_dystack pid=26772) Fitting model: NeuralNetFastAI_r102_BAG_L1 ... Training model for up to 282.08s of the 578.78s of remaining time.
(_dystack pid=26772) 	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=2, gpus=0, memory=0.09%)
(_ray_fit pid=16548) No improvement since epoch 0: early stopping
(_dystack pid=26772) 	-1814.3094	 = Validation score   (-mean_absolute_error)
(_dystack pid=26772) 	21.7s	 = Training   runtime
(_dystack pid=26772) 	0.22s	 = Validation runtime
(_dystack pid=26772) Fitting model: CatBoost_r13_BAG_L1 ... Training model for up to 256.22s of the 552.92s of remaining time.
(_dystack pid=26772) 	Memory not enough to fit 5 folds in parallel. Will train 2 folds in parallel instead (Estimated 34.13% memory usage per fold, 68.27%/80.00% total).
(_dystack pid=26772) 	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=6, gpus=0, memory=34.13%)